name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev, fix ]
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Python настройка
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Установить зависимости
      run: |
        # Автоматически находим, где лежит requirements.txt, и переходим туда
        TARGET_DIR=$(dirname $(find . -name "requirements.txt" -print -quit))
        cd "$TARGET_DIR"
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Запустить автотесты Selenium
      run: |
        # Автоматически находим, где лежит файл с тестами, и запускаем pytest внутри этой папки
        TARGET_DIR=$(dirname $(find . -name "test_ui.py" -print -quit))
        cd "$TARGET_DIR"
        pytest test.py

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./