name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev, fix ]
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Проверить репозиторий (Checkout)
      uses: actions/checkout@v4

    - name: Настроить Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Установить зависимости
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Запустить автотесты
      run: |
        pytest test.py

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Проверить репозиторий (Checkout)
      uses: actions/checkout@v4

    - name: Деплой на GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./